/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProductRouteImport } from './routes/_app/product'
import { Route as AppMyAdsRouteImport } from './routes/_app/my-ads'
import { Route as AppCreateAdRouteImport } from './routes/_app/create-ad'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AppProductProductIdRouteImport } from './routes/_app/product/$productId'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminCategoriesIndexRouteImport } from './routes/_admin/admin/categories/index'
import { Route as AppAdsAdIdEditRouteImport } from './routes/_app/ads/$adId/edit'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin/users/$userId'
import { Route as AdminAdminAdsAdIdRouteImport } from './routes/_admin/admin/ads/$adId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductRoute = AppProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAdsRoute = AppMyAdsRouteImport.update({
  id: '/my-ads',
  path: '/my-ads',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateAdRoute = AppCreateAdRouteImport.update({
  id: '/create-ad',
  path: '/create-ad',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AppProductProductIdRoute = AppProductProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCategoriesIndexRoute =
  AdminAdminCategoriesIndexRouteImport.update({
    id: '/admin/categories/',
    path: '/admin/categories/',
    getParentRoute: () => AdminRoute,
  } as any)
const AppAdsAdIdEditRoute = AppAdsAdIdEditRouteImport.update({
  id: '/ads/$adId/edit',
  path: '/ads/$adId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAdsAdIdRoute = AdminAdminAdsAdIdRouteImport.update({
  id: '/admin/ads/$adId',
  path: '/admin/ads/$adId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/create-ad': typeof AppCreateAdRoute
  '/my-ads': typeof AppMyAdsRoute
  '/product': typeof AppProductRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/product/$productId': typeof AppProductProductIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/ads/$adId': typeof AdminAdminAdsAdIdRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/ads/$adId/edit': typeof AppAdsAdIdEditRoute
  '/admin/categories/': typeof AdminAdminCategoriesIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/create-ad': typeof AppCreateAdRoute
  '/my-ads': typeof AppMyAdsRoute
  '/product': typeof AppProductRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/product/$productId': typeof AppProductProductIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/ads/$adId': typeof AdminAdminAdsAdIdRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/ads/$adId/edit': typeof AppAdsAdIdEditRoute
  '/admin/categories': typeof AdminAdminCategoriesIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/create-ad': typeof AppCreateAdRoute
  '/_app/my-ads': typeof AppMyAdsRoute
  '/_app/product': typeof AppProductRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/product/$productId': typeof AppProductProductIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/ads/$adId': typeof AdminAdminAdsAdIdRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/_app/ads/$adId/edit': typeof AppAdsAdIdEditRoute
  '/_admin/admin/categories/': typeof AdminAdminCategoriesIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-ad'
    | '/my-ads'
    | '/product'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/product/$productId'
    | '/admin/'
    | '/admin/ads/$adId'
    | '/admin/users/$userId'
    | '/ads/$adId/edit'
    | '/admin/categories/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-ad'
    | '/my-ads'
    | '/product'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/product/$productId'
    | '/admin'
    | '/admin/ads/$adId'
    | '/admin/users/$userId'
    | '/ads/$adId/edit'
    | '/admin/categories'
    | '/admin/users'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_app/create-ad'
    | '/_app/my-ads'
    | '/_app/product'
    | '/_app/profile'
    | '/auth/login'
    | '/auth/register'
    | '/_app/'
    | '/_app/product/$productId'
    | '/_admin/admin/'
    | '/_admin/admin/ads/$adId'
    | '/_admin/admin/users/$userId'
    | '/_app/ads/$adId/edit'
    | '/_admin/admin/categories/'
    | '/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product': {
      id: '/_app/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AppProductRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-ads': {
      id: '/_app/my-ads'
      path: '/my-ads'
      fullPath: '/my-ads'
      preLoaderRoute: typeof AppMyAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-ad': {
      id: '/_app/create-ad'
      path: '/create-ad'
      fullPath: '/create-ad'
      preLoaderRoute: typeof AppCreateAdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/product/$productId': {
      id: '/_app/product/$productId'
      path: '/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof AppProductProductIdRouteImport
      parentRoute: typeof AppProductRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/categories/': {
      id: '/_admin/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminAdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/ads/$adId/edit': {
      id: '/_app/ads/$adId/edit'
      path: '/ads/$adId/edit'
      fullPath: '/ads/$adId/edit'
      preLoaderRoute: typeof AppAdsAdIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/ads/$adId': {
      id: '/_admin/admin/ads/$adId'
      path: '/admin/ads/$adId'
      fullPath: '/admin/ads/$adId'
      preLoaderRoute: typeof AdminAdminAdsAdIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminAdsAdIdRoute: typeof AdminAdminAdsAdIdRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminCategoriesIndexRoute: typeof AdminAdminCategoriesIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminAdsAdIdRoute: AdminAdminAdsAdIdRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminCategoriesIndexRoute: AdminAdminCategoriesIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppProductRouteChildren {
  AppProductProductIdRoute: typeof AppProductProductIdRoute
}

const AppProductRouteChildren: AppProductRouteChildren = {
  AppProductProductIdRoute: AppProductProductIdRoute,
}

const AppProductRouteWithChildren = AppProductRoute._addFileChildren(
  AppProductRouteChildren,
)

interface AppRouteChildren {
  AppCreateAdRoute: typeof AppCreateAdRoute
  AppMyAdsRoute: typeof AppMyAdsRoute
  AppProductRoute: typeof AppProductRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdsAdIdEditRoute: typeof AppAdsAdIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateAdRoute: AppCreateAdRoute,
  AppMyAdsRoute: AppMyAdsRoute,
  AppProductRoute: AppProductRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdsAdIdEditRoute: AppAdsAdIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
