"""add boosts

Revision ID: 0e252bef1e57
Revises: 969596bfa18a
Create Date: 2026-08-30 15:21:00.377121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e252bef1e57'
down_revision: Union[str, Sequence[str], None] = '969596bfa18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boost_settings',
    sa.Column('regular_boost_count', sa.Integer(), nullable=False),
    sa.Column('trusted_boost_count', sa.Integer(), nullable=False),
    sa.Column('regular_boost_interval_days', sa.Integer(), nullable=False),
    sa.Column('trusted_boost_interval_days', sa.Integer(), nullable=False),
    sa.Column('regular_daily_limit', sa.Integer(), nullable=False),
    sa.Column('trusted_daily_limit', sa.Integer(), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('last_channel_boost_post_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boost_settings_created_at'), 'boost_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_boost_settings_updated_at'), 'boost_settings', ['updated_at'], unique=False)
    op.create_table('boost_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('boosted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boost_logs_ad_id'), 'boost_logs', ['ad_id'], unique=False)
    op.create_index(op.f('ix_boost_logs_created_at'), 'boost_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_boost_logs_updated_at'), 'boost_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_boost_logs_user_id'), 'boost_logs', ['user_id'], unique=False)
    op.create_table('channel_boost_queues',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_boost_queues_ad_id'), 'channel_boost_queues', ['ad_id'], unique=True)
    op.create_index(op.f('ix_channel_boost_queues_created_at'), 'channel_boost_queues', ['created_at'], unique=False)
    op.create_index(op.f('ix_channel_boost_queues_enqueued_at'), 'channel_boost_queues', ['enqueued_at'], unique=False)
    op.create_index(op.f('ix_channel_boost_queues_updated_at'), 'channel_boost_queues', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_boost_queues_updated_at'), table_name='channel_boost_queues')
    op.drop_index(op.f('ix_channel_boost_queues_enqueued_at'), table_name='channel_boost_queues')
    op.drop_index(op.f('ix_channel_boost_queues_created_at'), table_name='channel_boost_queues')
    op.drop_index(op.f('ix_channel_boost_queues_ad_id'), table_name='channel_boost_queues')
    op.drop_table('channel_boost_queues')
    op.drop_index(op.f('ix_boost_logs_user_id'), table_name='boost_logs')
    op.drop_index(op.f('ix_boost_logs_updated_at'), table_name='boost_logs')
    op.drop_index(op.f('ix_boost_logs_created_at'), table_name='boost_logs')
    op.drop_index(op.f('ix_boost_logs_ad_id'), table_name='boost_logs')
    op.drop_table('boost_logs')
    op.drop_index(op.f('ix_boost_settings_updated_at'), table_name='boost_settings')
    op.drop_index(op.f('ix_boost_settings_created_at'), table_name='boost_settings')
    op.drop_table('boost_settings')
    # ### end Alembic commands ###
