"""add category/subcategory models

Revision ID: 5ff7a3ba3d23
Revises: 94df565fb684
Create Date: 2026-06-18 00:59:10.088838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff7a3ba3d23'
down_revision: Union[str, Sequence[str], None] = '94df565fb684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('available_for', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_key'), 'categories', ['key'], unique=True)
    op.create_index(op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False)
    op.create_table('subcategory_groups',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_key'], ['categories.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_groups_category_key'), 'subcategory_groups', ['category_key'], unique=False)
    op.create_index(op.f('ix_subcategory_groups_created_at'), 'subcategory_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_subcategory_groups_key'), 'subcategory_groups', ['key'], unique=True)
    op.create_index(op.f('ix_subcategory_groups_updated_at'), 'subcategory_groups', ['updated_at'], unique=False)
    op.create_table('subcategories',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('requires_size', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_key', sa.String(length=64), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_key'], ['categories.key'], ),
    sa.ForeignKeyConstraint(['group_key'], ['subcategory_groups.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategories_category_key'), 'subcategories', ['category_key'], unique=False)
    op.create_index(op.f('ix_subcategories_created_at'), 'subcategories', ['created_at'], unique=False)
    op.create_index(op.f('ix_subcategories_group_key'), 'subcategories', ['group_key'], unique=False)
    op.create_index(op.f('ix_subcategories_key'), 'subcategories', ['key'], unique=False)
    op.create_index(op.f('ix_subcategories_updated_at'), 'subcategories', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategories_updated_at'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_key'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_group_key'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_created_at'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_key'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_subcategory_groups_updated_at'), table_name='subcategory_groups')
    op.drop_index(op.f('ix_subcategory_groups_key'), table_name='subcategory_groups')
    op.drop_index(op.f('ix_subcategory_groups_created_at'), table_name='subcategory_groups')
    op.drop_index(op.f('ix_subcategory_groups_category_key'), table_name='subcategory_groups')
    op.drop_table('subcategory_groups')
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_key'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
