"""sync

Revision ID: 6421b6221a22
Revises: 0e252bef1e57
Create Date: 2026-09-25 19:30:51.980373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6421b6221a22'
down_revision: Union[str, Sequence[str], None] = '0e252bef1e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_boost_queue_enqueued_at'), table_name='channel_boost_queue')
    op.drop_table('channel_boost_queue')
    op.add_column('boost_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('boost_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE boost_logs SET created_at = NOW()")
    op.alter_column('boost_logs', 'created_at', nullable=False)
    op.drop_index(op.f('idx_boost_logs_ad_id'), table_name='boost_logs')
    op.drop_index(op.f('idx_boost_logs_boosted_at'), table_name='boost_logs')
    op.drop_index(op.f('idx_boost_logs_user_id'), table_name='boost_logs')
    op.create_index(op.f('ix_boost_logs_ad_id'), 'boost_logs', ['ad_id'], unique=False)
    op.create_index(op.f('ix_boost_logs_created_at'), 'boost_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_boost_logs_updated_at'), 'boost_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_boost_logs_user_id'), 'boost_logs', ['user_id'], unique=False)
    op.alter_column('boost_settings', 'updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_boost_settings_created_at'), 'boost_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_boost_settings_updated_at'), 'boost_settings', ['updated_at'], unique=False)
    op.add_column('user_credentials', sa.Column('email_confirm_token', sa.String(length=132), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'email_confirm_token')
    op.drop_index(op.f('ix_boost_settings_updated_at'), table_name='boost_settings')
    op.drop_index(op.f('ix_boost_settings_created_at'), table_name='boost_settings')
    op.alter_column('boost_settings', 'updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_boost_logs_user_id'), table_name='boost_logs')
    op.drop_index(op.f('ix_boost_logs_updated_at'), table_name='boost_logs')
    op.drop_index(op.f('ix_boost_logs_created_at'), table_name='boost_logs')
    op.drop_index(op.f('ix_boost_logs_ad_id'), table_name='boost_logs')
    op.create_index(op.f('idx_boost_logs_user_id'), 'boost_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_boost_logs_boosted_at'), 'boost_logs', ['boosted_at'], unique=False)
    op.create_index(op.f('idx_boost_logs_ad_id'), 'boost_logs', ['ad_id'], unique=False)
    op.drop_column('boost_logs', 'updated_at')
    op.drop_column('boost_logs', 'created_at')
    op.create_table('channel_boost_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enqueued_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('channel_boost_queue_ad_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('channel_boost_queue_pkey')),
    sa.UniqueConstraint('ad_id', name=op.f('channel_boost_queue_ad_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_channel_boost_queue_enqueued_at'), 'channel_boost_queue', ['enqueued_at'], unique=False)
    # ### end Alembic commands ###
