"""add_user_credentials

Revision ID: 94df565fb684
Revises: f9fedebf1890
Create Date: 2026-06-11 00:08:53.279807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94df565fb684'
down_revision: Union[str, Sequence[str], None] = 'f9fedebf1890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_confirm_token', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_user_credentials_created_at'), 'user_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_credentials_email'), 'user_credentials', ['email'], unique=True)
    op.create_index(op.f('ix_user_credentials_updated_at'), 'user_credentials', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('user_credentials', 'email_confirm_token')
    except:
        print("WARN: Failed to drop email_confirm_token")

    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.drop_index(op.f('ix_user_credentials_updated_at'), table_name='user_credentials')
    op.drop_index(op.f('ix_user_credentials_email'), table_name='user_credentials')
    op.drop_index(op.f('ix_user_credentials_created_at'), table_name='user_credentials')
    op.drop_table('user_credentials')
    # ### end Alembic commands ###
