"""sync with bot

Revision ID: 969596bfa18a
Revises: d_add_contact_value
Create Date: 2026-08-30 15:00:42.167564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969596bfa18a'
down_revision: Union[str, Sequence[str], None] = 'd_add_contact_value'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # try:
    #     op.add_column('ads', sa.Column('boost_count', sa.Integer(), nullable=False, server_default="0"))
    #     op.add_column('ads', sa.Column('last_boost_at', sa.DateTime(), nullable=True))
    #     op.add_column('ads', sa.Column('next_boost_at', sa.DateTime(), nullable=True))
    #     op.add_column('ads', sa.Column('boost_reminder_step', sa.Integer(), nullable=False, server_default="0"))
    #     op.add_column('ads', sa.Column('boost_reminder_sent_at', sa.DateTime(), nullable=True))
    #     op.add_column('ads', sa.Column('boost_first_reminder_at', sa.DateTime(), nullable=True))
    #     op.add_column('ads', sa.Column('boost_confirmed', sa.Boolean(), nullable=False, server_default="false"))
    #     op.add_column('ads', sa.Column('inactive_since', sa.DateTime(), nullable=True))
    # except Exception as e:
    #     print(f"ERR UPGRADE BOOSTS: {e}\npassed...")
    op.alter_column('blacklist', 'tg_user_id',
               nullable=True)
    op.alter_column('notifications', 'created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('blacklist', 'tg_user_id',
               nullable=False)
    op.drop_column('ads', 'inactive_since')
    op.drop_column('ads', 'boost_confirmed')
    op.drop_column('ads', 'boost_first_reminder_at')
    op.drop_column('ads', 'boost_reminder_sent_at')
    op.drop_column('ads', 'boost_reminder_step')
    op.drop_column('ads', 'next_boost_at')
    op.drop_column('ads', 'last_boost_at')
    op.drop_column('ads', 'boost_count')
    # ### end Alembic commands ###
