"""check_sync

Revision ID: f9fedebf1890
Revises: f0171670b703
Create Date: 2026-06-10 23:52:24.470818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fedebf1890'
down_revision: Union[str, Sequence[str], None] = 'f0171670b703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_edit_photos', 'file_id',
               nullable=True)
    op.drop_index(op.f('ix_ad_edit_photos_id'), table_name='ad_edit_photos')
    op.create_index(op.f('ix_ad_edit_photos_created_at'), 'ad_edit_photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_ad_edit_photos_updated_at'), 'ad_edit_photos', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_ad_edits_id'), table_name='ad_edits')
    op.create_index(op.f('ix_ad_edits_created_at'), 'ad_edits', ['created_at'], unique=False)
    op.create_index(op.f('ix_ad_edits_updated_at'), 'ad_edits', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_ad_photos_id'), table_name='ad_photos')
    op.create_index(op.f('ix_ad_photos_created_at'), 'ad_photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_ad_photos_updated_at'), 'ad_photos', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.create_index(op.f('ix_ads_created_at'), 'ads', ['created_at'], unique=False)
    op.create_index(op.f('ix_ads_updated_at'), 'ads', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_blacklist_id'), table_name='blacklist')
    op.create_index(op.f('ix_blacklist_created_at'), 'blacklist', ['created_at'], unique=False)
    op.create_index(op.f('ix_blacklist_updated_at'), 'blacklist', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_contact_logs_id'), table_name='contact_logs')
    op.create_index(op.f('ix_contact_logs_created_at'), 'contact_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_logs_updated_at'), 'contact_logs', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_delete_messages_id'), table_name='delete_messages')
    op.create_index(op.f('ix_delete_messages_created_at'), 'delete_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_delete_messages_updated_at'), 'delete_messages', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_details_logs_id'), table_name='details_logs')
    op.create_index(op.f('ix_details_logs_created_at'), 'details_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_details_logs_updated_at'), 'details_logs', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_updated_at'), 'reviews', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_tags_updated_at'), 'tags', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_tags_updated_at'), table_name='tags')
    op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.drop_index(op.f('ix_reviews_updated_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_index(op.f('ix_details_logs_updated_at'), table_name='details_logs')
    op.drop_index(op.f('ix_details_logs_created_at'), table_name='details_logs')
    op.create_index(op.f('ix_details_logs_id'), 'details_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_delete_messages_updated_at'), table_name='delete_messages')
    op.drop_index(op.f('ix_delete_messages_created_at'), table_name='delete_messages')
    op.create_index(op.f('ix_delete_messages_id'), 'delete_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_contact_logs_updated_at'), table_name='contact_logs')
    op.drop_index(op.f('ix_contact_logs_created_at'), table_name='contact_logs')
    op.create_index(op.f('ix_contact_logs_id'), 'contact_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_blacklist_updated_at'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_created_at'), table_name='blacklist')
    op.create_index(op.f('ix_blacklist_id'), 'blacklist', ['id'], unique=False)
    op.drop_index(op.f('ix_ads_updated_at'), table_name='ads')
    op.drop_index(op.f('ix_ads_created_at'), table_name='ads')
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    op.drop_index(op.f('ix_ad_photos_updated_at'), table_name='ad_photos')
    op.drop_index(op.f('ix_ad_photos_created_at'), table_name='ad_photos')
    op.create_index(op.f('ix_ad_photos_id'), 'ad_photos', ['id'], unique=False)
    op.drop_index(op.f('ix_ad_edits_updated_at'), table_name='ad_edits')
    op.drop_index(op.f('ix_ad_edits_created_at'), table_name='ad_edits')
    op.create_index(op.f('ix_ad_edits_id'), 'ad_edits', ['id'], unique=False)
    op.drop_index(op.f('ix_ad_edit_photos_updated_at'), table_name='ad_edit_photos')
    op.drop_index(op.f('ix_ad_edit_photos_created_at'), table_name='ad_edit_photos')
    op.create_index(op.f('ix_ad_edit_photos_id'), 'ad_edit_photos', ['id'], unique=False)
    op.alter_column('ad_edit_photos', 'file_id',
               nullable=False)
    # ### end Alembic commands ###
